# -*- coding: utf-8 -*-
"""snack_modeliing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCr7UGh-FinOWYvbscI9IEnO3hHKVrVq
"""

import pandas as pd
import csv

data = pd.read_csv('walmart_pp.csv', encoding='CP949')
df = pd.DataFrame(data, columns= ['score', 'comment'])
#df2 = df[df['score'] < 3]
#df2.to_csv('wal_snack1~2.csv')

import pandas as pd
from collections import Counter
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import nltk
import csv

data = pd.read_csv('walmart_pp.csv', encoding='CP949')
df = pd.DataFrame(data, columns= ['score', 'comment'])
df2 = df[df['score'] < 3]

nltk.download('stopwords')
data = []
col = 'comment'
#df2= pd.read_csv("walmart_snack(REAL).csv", encoding='CP949')
stop_words = nltk.corpus.stopwords.words('english')
stop_words.extend(['crackers','go','loved','time','get','pack','eat','buy','cracker','chip','chips','promotion','nani','part','review','collected','also','delicious','taste','really', "ocean's", 'snack', 'flavor', 'snacks', 'snack', 'flavor', 'like', 'good', 'love', 'great', 'would', 'one', 'product','bag','box'])

def wordCloud(df2):
    text = ''
    for i in range(len(df2.index)):
        data.append(df2[col].iloc[i])
    for i in data:
        text += str(i)
    for char in '-.,\n;[]':
        text = text.replace(char,' ')
    text = text.lower()
    wc = WordCloud(stopwords = stop_words, background_color='white', max_words=20, collocations=False)
    wc.generate(text)

    plt.imshow(wc, interpolation='bilinear')
    plt.axis("off")
    plt.show()


wordCloud(df2)
#wordCloud(dfpos)
#wordCloud(dfneg)

data = pd.read_csv('walmart_snack(REAL).csv', encoding='CP949')
df = pd.DataFrame(data, columns= ['score', 'comment'])
df5 = df[df['score'] > 3]
df5.to_csv('wal_snack4~5.csv')

import pandas as pd
from collections import Counter
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import nltk
nltk.download('stopwords')
data = []
col = 'comment'
stop_words = nltk.corpus.stopwords.words('english')
stop_words.extend(['pack','part','review','collected','promotion','also','delicious','taste','really', "ocean's", 'snack', 'flavor', 'snacks', 'snack', 'flavor', 'like', 'good', 'love', 'great', 'would', 'one', 'product','bag','box'])

def wordCloud(df5):
    text = ''
    for i in range(len(df5.index)):
        data.append(df5[col].iloc[i])
    for i in data:
        text += str(i)
    for char in '-.,\n;[]':
        text = text.replace(char,' ')
    text = text.lower()
    wc = WordCloud(stopwords = stop_words, background_color='white', max_words=30, collocations=False)
    wc.generate(text)

    plt.imshow(wc, interpolation='bilinear')
    plt.axis("off")
    plt.show()


wordCloud(df5)
#wordCloud(dfpos)
#wordCloud(dfneg)